### ISSUE TITLE
Error when trying to import to QS Enterprise Jun 2019

### ISSUE THREAD

**Issue by QlikMaster** [miralemd/mekaarogram#3]
<img width="590" alt="Screen Shot 2019-08-13 at 11 15 28 AM" src="https://user-images.githubusercontent.com/23746710/62958130-b41f6080-bdbb-11e9-8697-bf012c8629b5.png">

**Comment by miralemd** [comment]
`mekaarogram-master.zip` sounds like a zip of this entire repo was attempted to be uploaded which won't work, try using the zip files attached to a [release](https://github.com/miralemd/mekaarogram/releases)
